version: "3.9"
services:
  db:
    image: ankane/pgvector:latest
    container_name: ai_kb_pg
    environment:
      POSTGRES_USER: aiuser
      POSTGRES_PASSWORD: aistrongpass
      POSTGRES_DB: aikb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
